# 
# Synthesis run script generated by Vivado
# 

set_msg_config -id {HDL 9-1061} -limit 100000
set_msg_config -id {HDL 9-1654} -limit 100000
create_project -in_memory -part xc7a50ticsg325-1L

set_param project.compositeFile.enableAutoGeneration 0
set_param synth.vivado.isSynthRun true
set_property webtalk.parent_dir C:/Users/Mad/project_fft_dif_8/project_fft_dif_8.cache/wt [current_project]
set_property parent.project_path C:/Users/Mad/project_fft_dif_8/project_fft_dif_8.xpr [current_project]
set_property default_lib xil_defaultlib [current_project]
set_property target_language VHDL [current_project]
set_property vhdl_version vhdl_2k [current_fileset]
read_vhdl -library xil_defaultlib {
  C:/Users/Mad/project_fft_dif_8/project_fft_dif_8.srcs/sources_1/new/pkg_complex.vhd
  C:/Users/Mad/project_fft_dif_8/project_fft_dif_8.srcs/sources_1/new/butterfly.vhd
  C:/Users/Mad/project_fft_dif_8/project_fft_dif_8.srcs/sources_1/new/fft_dif_8.vhd
}
synth_design -top fft_dif_8 -part xc7a50ticsg325-1L
write_checkpoint -noxdef fft_dif_8.dcp
catch { report_utilization -file fft_dif_8_utilization_synth.rpt -pb fft_dif_8_utilization_synth.pb }
